namespace ClaudeUsageWidget;

public enum UiLanguage { ZhHant = 0, En = 1 }

/// <summary>Tiny string table for the two supported UI languages.</summary>
public static class L10n
{
    public static UiLanguage Lang { get; private set; } = UiLanguage.ZhHant;
    public static event Action? Changed;

    public static void Set(UiLanguage lang)
    {
        if (Lang == lang) return;
        Lang = lang;
        Changed?.Invoke();
    }

    public static void Init(UiLanguage lang) => Lang = lang;

    public static string T(string key) =>
        Table.TryGetValue(key, out var pair) ? (Lang == UiLanguage.En ? pair.en : pair.zh) : key;

    public static string F(string key, params object[] args) => string.Format(T(key), args);

    static readonly Dictionary<string, (string zh, string en)> Table = new()
    {
        // widget
        ["widget_title"] = ("AI 用量", "AI Usage"),
        ["provider_claude"] = ("Claude", "Claude"),
        ["provider_chatgpt"] = ("ChatGPT", "ChatGPT"),
        ["strip_provider_codex"] = ("GPT", "GPT"),
        ["strip_provider_claude"] = ("Claude", "Claude"),
        ["strip_working_tooltip"] = ("{0} 個 AI 任務正在工作", "{0} AI tasks working"),
        ["strip_runway_runs_out"] = ("{0}：以目前速度約 {1} 用完（{2} 後重置）", "{0}: at the current rate, runs out in ~{1} (resets in {2})"),
        ["strip_runway_low_left"] = ("{0}：只剩 {1}%", "{0}: only {1}% left"),
        ["pane_runway_runs_out"] = ("以目前速度約 {0} 用完（{1} 後重置）", "At the current rate: runs out in ~{0} (resets in {1})"),
        ["pane_runway_lasts"] = ("以目前速度可撐到重置", "At the current rate: lasts until reset"),
        ["pane_runway_unknown"] = ("尚無足夠資料估算用量速度", "Not enough readings yet to estimate the rate"),
        ["strip_done_tooltip"] = ("{0} 個任務在過去 {1} 分鐘內完成", "{0} tasks finished in the last {1} minutes"),
        ["strip_done_failed_tooltip"] = ("{0} 個任務完成，{1} 個失敗（過去 {2} 分鐘）", "{0} finished, {1} failed in the last {2} minutes"),
        ["strip_attention_tooltip"] = ("{0} 個任務需要你的注意", "{0} tasks need your attention"),
        ["notification_needs_you"] = ("需要你處理", "needs you"),
        ["notification_finished"] = ("已完成", "finished"),
        ["notification_failed"] = ("失敗", "failed"),
        ["pane_codex"] = ("CODEX", "CODEX"),
        ["pane_claude"] = ("CLAUDE", "CLAUDE"),
        ["pane_needs_you"] = ("需要你處理", "NEEDS YOU"),
        ["pane_working"] = ("正在執行", "WORKING"),
        ["pane_unknown"] = ("狀態不明", "UNKNOWN"),
        ["pane_recent"] = ("最近完成", "RECENTLY COMPLETED"),
        ["pane_empty_tasks"] = ("目前沒有執行中的 AI 任務", "No AI tasks running"),
        ["pane_dismiss"] = ("隱藏", "Dismiss"),
        ["pane_provider_codex"] = ("Codex", "Codex"),
        ["pane_provider_claude"] = ("Claude", "Claude"),
        ["pane_status_detail"] = ("狀態：{0}", "Status: {0}"),
        ["pane_attention_reason"] = ("需要注意：{0}", "Needs attention: {0}"),
        ["pane_confidence"] = ("判斷依據：{0}", "Confidence: {0}"),
        ["pane_confidence_confirmed"] = ("已確認", "Confirmed"),
        ["pane_confidence_inferred"] = ("推測", "Inferred"),
        ["pane_confidence_stale"] = ("可能過期", "Stale"),
        ["pane_activity_just_now"] = ("最後活動：剛剛", "Last activity: just now"),
        ["pane_age_now"] = ("剛剛", "now"),
        ["pane_age_minutes"] = ("{0} 分", "{0}m"),
        ["pane_age_hours"] = ("{0} 時", "{0}h"),
        ["pane_age_days"] = ("{0} 天", "{0}d"),
        ["pane_activity_minutes_ago"] = ("最後活動：{0} 分鐘前", "Last activity: {0} min ago"),
        ["pane_activity_hours_ago"] = ("最後活動：{0} 小時前", "Last activity: {0} hr ago"),
        ["pane_activity_days_ago"] = ("最後活動：{0} 天前", "Last activity: {0} days ago"),
        ["tray_usage_remaining"] = ("剩餘 {0}%", "{0}% remaining"),
        ["tray_usage_unavailable"] = ("無可用資料", "unavailable"),
        ["tray_usage_stale"] = (" · 過期", " · stale"),
        ["updating"] = ("更新中…", "Updating…"),
        ["data_stale"] = ("資料可能已過期 · {0}", "Data may be stale · {0}"),
        ["retry_at"] = ("{0} 重試", "retry {0}"),
        ["reset_soon"] = ("即將重置", "Resets soon"),
        ["reset_days"] = ("{0} 天 {1} 時後重置", "Resets in {0}d {1}h"),
        ["reset_hours"] = ("{0} 時 {1} 分後重置", "Resets in {0}h {1}m"),
        ["reset_mins"] = ("{0} 分後重置", "Resets in {0}m"),
        // menus
        ["menu_refresh"] = ("立即更新", "Refresh now"),
        ["menu_hide_strip"] = ("隱藏狀態列", "Hide status strip"),
        ["menu_show_strip"] = ("顯示狀態列", "Show status strip"),
        ["menu_expand_pane"] = ("展開詳細資訊", "Expand details pane"),
        ["menu_collapse_pane"] = ("收合詳細資訊", "Collapse details pane"),
        ["menu_sign_in"] = ("登入服務", "Sign in"),
        ["menu_sign_in_codex"] = ("ChatGPT / Codex", "ChatGPT / Codex"),
        ["menu_hide"] = ("隱藏小工具", "Hide widget"),
        ["menu_showhide"] = ("顯示 / 隱藏小工具", "Show / hide widget"),
        ["menu_provider"] = ("查看服務", "View provider"),
        ["menu_settings"] = ("設定…", "Settings…"),
        ["menu_copy_diagnostics"] = ("複製診斷資訊", "Copy diagnostic information"),
        ["menu_save_diagnostic_bundle"] = ("儲存診斷封包…", "Save diagnostic bundle…"),
        ["menu_autostart"] = ("開機自動啟動", "Start with Windows"),
        ["menu_relogin"] = ("連結 / 重新登入", "Connect / sign in again"),
        ["menu_exit"] = ("結束", "Exit"),
        ["menu_reset_position"] = ("重設視窗位置", "Reset window position"),
        ["diagnostics_copied"] = ("已複製不含私人資料的診斷資訊。", "Redacted diagnostic information copied."),
        ["diagnostics_copy_failed"] = ("無法複製診斷資訊：{0}", "Could not copy diagnostics: {0}"),
        ["diagnostics_save_title"] = ("儲存診斷封包", "Save diagnostic bundle"),
        ["diagnostics_zip_filter"] = ("診斷封包 (*.zip)|*.zip", "Diagnostic bundle (*.zip)|*.zip"),
        ["diagnostics_saved"] = ("診斷封包已儲存。", "Diagnostic bundle saved."),
        ["diagnostics_save_failed"] = ("無法儲存診斷封包：{0}", "Could not save diagnostics: {0}"),
        ["autostart_problem"] = ("Windows 無法完整套用開機自動啟動設定（{0}）。請檢查「啟動」資料夾權限或公司裝置政策。", "Windows could not fully apply the auto-start setting ({0}). Check the Startup folder permission or your organization device policy."),
        // errors / status
        ["err_update_prefix"] = ("更新失敗:{0}", "Update failed: {0}"),
        ["err_usage_unavailable"] = ("目前無法取得用量資料。", "Usage is temporarily unavailable."),
        ["err_not_signed_in_hint"] = ("尚未登入，右鍵選「登入服務 › Claude」。", "Not signed in — right-click and choose \"Sign in › Claude\"."),
        ["tray_need_login"] = ("AI Usage — 需要登入", "AI Usage — sign-in required"),
        ["err_not_signed_in"] = ("尚未登入", "Not signed in"),
        ["err_token_expired"] = (
            "Claude 登入已過期。請在小工具或系統匣圖示上按右鍵，選擇「登入服務 › Claude」，再依畫面完成登入。",
            "Claude sign-in has expired. Right-click the widget or tray icon, choose \"Sign in › Claude\", and complete the sign-in steps."),
        ["err_refresh_failed"] = ("Token 刷新失敗,請重新登入({0})", "Token refresh failed — please sign in again ({0})"),
        ["err_network"] = ("網路暫時無法連線({0})", "Network temporarily unavailable ({0})"),
        ["err_schema_changed"] = ("無法解析用量資料,API 格式可能已變更。請「檢查更新」,若已是最新版請到 GitHub 回報。", "Couldn't parse usage data — the API format may have changed. Try \"Check for updates\", or report it on GitHub if you're up to date."),
        ["err_codex_start"] = ("無法啟動 Codex app-server。", "Couldn't start Codex app-server."),
        ["err_codex_missing"] = ("找不到或無法執行 Codex：{0}。請先安裝官方 Codex，或在設定中指定 codex.exe / codex.cmd。", "Codex couldn't be found or started: {0}. Install the official Codex CLI, or choose codex.exe / codex.cmd in Settings."),
        ["err_codex_path_invalid"] = ("設定的 Codex 路徑不存在：{0}", "The configured Codex path doesn't exist: {0}"),
        ["err_codex_stopped"] = ("Codex app-server 已停止，請稍後重試。", "Codex app-server stopped. Try again in a moment."),
        ["err_chatgpt_not_signed_in"] = ("小工具的 Codex CLI 尚未獲得 ChatGPT 授權（不影響桌面版登入）。請右鍵選「登入服務 › ChatGPT / Codex」完成一次授權。", "The widget's Codex CLI is not authorized with ChatGPT yet (your desktop app remains signed in). Right-click and choose \"Sign in › ChatGPT / Codex\" once."),
        ["err_chatgpt_no_limits"] = ("OpenAI 目前沒有回傳可顯示的 Codex 用量額度。", "OpenAI didn't return any displayable Codex quota windows."),
        ["err_chatgpt_login_start"] = ("Codex 沒有回傳登入網址，請更新 Codex 後再試一次。", "Codex didn't return a sign-in URL. Update Codex and try again."),
        ["err_chatgpt_login_timeout"] = ("等待 ChatGPT 登入逾時，請再試一次。", "Timed out waiting for ChatGPT sign-in. Try again."),
        ["chatgpt_login_waiting"] = ("瀏覽器已開啟，請完成 ChatGPT 登入…", "Browser opened — finish signing in to ChatGPT…"),
        ["chatgpt_login_replaces_api_key"] = ("Codex 目前使用 API key 模式。改用 ChatGPT 登入會替換 Codex 的主要登入方式。要繼續嗎？", "Codex is currently using API-key mode. Signing in with ChatGPT will replace Codex's primary login. Continue?"),
        ["chatgpt_limit_5h"] = ("5 小時額度", "5-hour limit"),
        ["chatgpt_limit_weekly"] = ("每週額度", "Weekly limit"),
        ["chatgpt_limit_monthly"] = ("每月額度", "Monthly limit"),
        ["chatgpt_limit_days"] = ("{0} 天額度", "{0}-day limit"),
        ["chatgpt_limit_hours"] = ("{0} 小時額度", "{0}-hour limit"),
        ["chatgpt_limit_minutes"] = ("{0} 分鐘額度", "{0}-minute limit"),
        ["chatgpt_limit_primary"] = ("主要額度", "Primary limit"),
        ["chatgpt_limit_secondary"] = ("次要額度", "Secondary limit"),
        // login window
        ["login_title"] = ("登入 Claude 帳號", "Sign in to Claude"),
        ["login_heading"] = ("連結你的 Claude 帳號", "Connect your Claude account"),
        ["login_body"] = (
            "這個工具需要讀取你的 Claude 方案使用量。按下方按鈕會開啟瀏覽器,用你的 Claude 帳號登入並授權(和 Claude Code 的 /login 是同一套流程)。授權後 token 只會加密儲存在這台電腦上。",
            "This tool reads your Claude plan usage. The button below opens your browser to sign in and authorize with your Claude account (the same flow Claude Code's /login uses). Tokens are stored encrypted on this PC only."),
        ["login_browser_btn"] = ("開啟瀏覽器登入", "Sign in with browser"),
        ["login_waiting"] = ("已開啟瀏覽器,等待你完成授權…", "Browser opened — waiting for you to authorize…"),
        ["login_timeout"] = ("等待逾時或已取消。可以重試,或改用下方的手動模式。", "Timed out or cancelled. Try again, or use manual mode below."),
        ["login_failed_with_hint"] = ("登入失敗:{0}\n可以改用下方的手動模式。", "Sign-in failed: {0}\nYou can also try manual mode below."),
        ["login_failed"] = ("登入失敗:{0}", "Sign-in failed: {0}"),
        ["login_manual_expander"] = ("瀏覽器沒有自動完成?改用手動貼上", "Browser didn't finish automatically? Paste the code manually"),
        ["login_manual_steps"] = (
            "1. 按下面按鈕開啟登入頁(授權後頁面會顯示一段代碼)\n2. 複製整段代碼貼到下方,按「完成登入」",
            "1. Click the button below to open the sign-in page (a code is shown after authorizing)\n2. Copy the whole code, paste it below and click \"Complete sign-in\""),
        ["login_manual_open"] = ("開啟登入頁面(手動模式)", "Open sign-in page (manual mode)"),
        ["login_manual_submit"] = ("完成登入", "Complete sign-in"),
        ["login_manual_opened"] = ("已開啟手動登入頁,授權後把顯示的代碼貼到下方。", "Manual sign-in page opened — paste the code shown after authorizing."),
        ["login_paste_first"] = ("請先貼上代碼。", "Paste the code first."),
        ["login_open_failed"] = ("開啟失敗:{0}", "Failed to open: {0}"),
        ["oauth_state_mismatch"] = ("OAuth state 不符,已中止。", "OAuth state mismatch — aborted."),
        ["oauth_click_open_first"] = ("請先按「開啟登入頁面」再貼上代碼。", "Click \"Open sign-in page\" first, then paste the code."),
        ["browser_success"] = ("登入成功", "Signed in"),
        ["browser_success_body"] = ("可以關閉這個分頁,回到 Claude Usage Widget。", "You can close this tab and return to Claude Usage Widget."),
        ["browser_no_code"] = ("未收到授權碼", "No authorization code received"),
        ["browser_no_code_body"] = ("請回到工具重試。", "Please return to the app and try again."),
        // settings window
        ["settings_title"] = ("設定", "Settings"),
        ["settings_language"] = ("語言", "Language"),
        ["settings_theme"] = ("主題", "Theme"),
        ["theme_dark"] = ("深色", "Dark"),
        ["theme_light"] = ("淺色", "Light"),
        ["settings_opacity"] = ("背景透明度", "Background transparency"),
        ["settings_opacity_hint"] = ("0% 不透明,100% 完全透明", "0% solid — 100% fully transparent"),
        ["settings_notifications"] = ("需要你處理時通知", "Notify when tasks need you"),
        ["settings_finished_notifications"] = ("已完成任務的通知", "Notify when tasks finish"),
        ["settings_recent_completed"] = ("已完成任務保留分鐘數", "Keep completed tasks for (minutes)"),
        ["settings_pane_auto_collapse"] = ("詳細資訊閒置後收合", "Collapse pane after inactivity"),
        ["settings_auto_collapse_off"] = ("永不", "Never"),
        ["settings_auto_collapse_seconds"] = ("{0} 秒", "{0} seconds"),
        ["settings_attention_label"] = ("需要你處理時顯示的標籤", "Attention label"),
        ["settings_monitor"] = ("狀態列顯示器", "Status strip display"),
        ["settings_monitor_primary_display"] = ("主要顯示器：{0}（{1} × {2}）", "Primary display: {0} ({1} × {2})"),
        ["settings_monitor_display"] = ("顯示器 {0}：{1}（{2} × {3}）", "Display {0}: {1} ({2} × {3})"),
        ["settings_codex_home"] = ("Codex 資料夾（選填）", "Codex data folder (optional)"),
        ["settings_claude_code_home"] = ("Claude Code 資料夾（選填）", "Claude Code data folder (optional)"),
        ["settings_claude_hooks"] = ("使用 Claude Code hooks 顯示精確狀態（選填）", "Use Claude Code hooks for exact status (optional)"),
        ["settings_claude_hooks_hint"] = ("顯示權限請求與提問的確切狀態。會在 Claude Code 設定中加入四個 hook，並保留其他設定；停用時會移除。", "Shows permission prompts and questions exactly. Adds four hooks to your Claude Code settings, keeping everything else; turning this off removes them."),
        ["settings_claude_hooks_preview_show"] = ("顯示將加入的內容", "Show what will be added"),
        ["settings_claude_hooks_preview_hide"] = ("隱藏預覽", "Hide preview"),
        ["settings_section_general"] = ("一般", "GENERAL"),
        ["settings_section_display"] = ("狀態列與面板", "STRIP AND PANE"),
        ["settings_section_alerts"] = ("通知", "ALERTS"),
        ["settings_section_sources"] = ("資料來源", "DATA SOURCES"),
        ["settings_data_folder_hint"] = (@"留空即使用預設位置（%USERPROFILE%\.codex 與 %USERPROFILE%\.claude）。", @"Leave blank to use the defaults (%USERPROFILE%\.codex and %USERPROFILE%\.claude)."),
        ["settings_claude_hooks_error"] = ("無法更新 Claude Code 設定，因此沒有變更。請檢查設定檔是否有效及資料夾是否可寫入。", "Claude Code settings could not be updated, so no change was made. Check that the settings file is valid and its folder is writable."),
        ["settings_cowork_root"] = ("Cowork 資料夾（選填）", "Cowork data folder (optional)"),
        ["settings_threshold_approaching"] = ("接近用量上限（剩餘低於 %）", "Approaching limit below remaining (%)"),
        ["settings_threshold_low"] = ("用量偏低（剩餘低於 %）", "Low allowance below remaining (%)"),
        ["settings_demo_tasks"] = ("顯示示範任務", "Show demo tasks"),
        ["settings_codex_path"] = ("Codex 執行檔（選填）", "Codex executable (optional)"),
        ["settings_codex_browse"] = ("瀏覽…", "Browse…"),
        ["settings_codex_hint"] = ("留空會自動搜尋 ChatGPT 桌面版與 PATH；ChatGPT 用量由官方 Codex app-server 提供。", "Leave blank to search the ChatGPT desktop app and PATH. ChatGPT usage is provided by the official Codex app-server."),
        // updater
        ["menu_check_update"] = ("檢查更新", "Check for updates"),
        ["update_title"] = ("軟體更新", "Software update"),
        ["update_none"] = ("目前已是最新版本 (v{0})。", "You're on the latest version (v{0})."),
        ["update_found"] = ("發現新版本 v{0}(目前為 v{1})。\n要現在下載並自動更新嗎?", "Version v{0} is available (you have v{1}).\nDownload and update now?"),
        ["update_downloading"] = ("下載更新中…", "Downloading update…"),
        ["update_download_progress"] = ("下載更新：{0}%（{1} / {2} MB）", "Downloading update: {0}% ({1} / {2} MB)"),
        ["update_download_unknown"] = ("正在下載更新…", "Downloading update…"),
        ["update_verifying"] = ("正在驗證更新檔…", "Verifying update…"),
        ["update_extracting"] = ("正在解壓縮更新檔…", "Extracting update…"),
        ["update_applying"] = ("正在安裝更新…", "Installing update…"),
        ["update_restarting"] = ("正在重新啟動…", "Restarting…"),
        ["update_cancel"] = ("取消", "Cancel"),
        ["update_cancelled"] = ("已取消更新。", "Update cancelled."),
        ["update_failed"] = ("更新失敗:{0}", "Update failed: {0}"),
        ["update_balloon"] = ("有新版本 v{0} 可用,點此更新", "New version v{0} available — click to update"),
        ["settings_interval"] = ("更新頻率", "Refresh interval"),
        ["interval_60"] = ("每 60 秒", "Every 60 s"),
        ["interval_90"] = ("每 90 秒(建議)", "Every 90 s (recommended)"),
        ["interval_120"] = ("每 2 分鐘", "Every 2 min"),
        ["interval_300"] = ("每 5 分鐘", "Every 5 min"),
    };
}
